name: Generate Fantasy DFS Article

on:
  schedule:
    - cron: '0 16 * * *'  # 10:00 AM MST = 16:00 UTC
  workflow_dispatch:       # allows manual runs

jobs:
  generate_dfs_article:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install openai boto3 pandas

      - name: Run article generator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          python shared/generate_dfs_article.py
