name: generate_dfs_article

on:
  schedule:
    - cron: '0 16 * * *'  # Runs at 10:00 AM MST (16:00 UTC)
  workflow_dispatch:

jobs:
  run-generator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run article generator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python shared/generate_dfs_article.py
