name: Run Generate DFS Article

on:
  workflow_dispatch:
  schedule:
    - cron: '16 16 * * *'  # runs at 10:16am MST (16:16 UTC)

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .  # so imports like shared.openai_utils work

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run article generator
        run: python shared/generate_dfs_article.py
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
