name: Run Generate DFS Article

on:
  workflow_dispatch:
  schedule:
    - cron: "16 16 * * *"  # runs daily at 4:16 PM UTC (10:16 AM MST)

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Add repo root to PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

      - name: Run article generator
        run: python shared/generate_dfs_article.py
