name: Run Reddit Music News Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'  # Runs daily at 2PM UTC

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./reddit_news/music_news

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log runner’s current working directory
        run: |
          echo "PWD (from job root): $PWD"

      - name: List entire directory tree from root
        run: |
          echo "Directory tree from repo root:"
          ls -R

      - name: List contents of music_news folder
        run: |
          echo "Contents of reddit_news/music_news:"
          ls -la ./reddit_news/music_news

      - name: Run reddit_music_news_scraper.py
        run: python reddit_music_news_scraper.py

